### PR TITLE
Set up basic project layout and CI

### PR DESCRIPTION
**Pull request by arkn98**
This PR does the following things:

- Sets up a basic project layout as suggested by [golang-standards](https://github.com/golang-standards/project-layout).
- Sets up a basic CI pipeline for building & testing for the following events:
    - pushes to all branches, except `master` and `develop` branches because they're protected and don't allow a direct `git push`
    - PRs to `master` and `develop` branches

### CODE REVIEW

**Comment by dyaneshvarun** [comment]
Workflows are cool !

**Comment by arkn98** [comment]
We need to merge this to `master`.
@dyaneshvarun your thoughts?

**Comment by dyaneshvarun** [comment]
Generally, there are only 2 branches, the _feature_ branch and the _master_ branch. 

Feature will be the development branch and master would be the release branch. In case , if you want a branch to test all your changes you can have a 3rd branch named as _staging_ branch and then push your changes. Feature would be the branch for your development and the branch name would be like _feature/feature_name_here_ . So everyone shall raise PRs only to staging branch and staging can be pulled by other users for developing over and above it. 

Feature -> Staging
Staging -> Master

Staging will be pushed to master branch only in the next release date. This is generally a CI/CD flow.

Do let me know your thoughts . This branch can be merged to feature/master branch  as it builds properly !

**Comment by arkn98** [comment]
I feel like the branching model listed here [https://nvie.com/posts/a-successful-git-branching-model/](https://nvie.com/posts/a-successful-git-branching-model/) will be more suitable for our workflow. Do have a look at it.

**Comment by dyaneshvarun** [comment]
https://nvie.com/posts/a-successful-git-branching-model/ Looks cool. Similar to what I was talking about.

**Comment by arkn98** [comment]
Can we use that instead?

**Pull request merged**
